### ISSUE TITLE
hash bang choke

### ISSUE THREAD

**Issue by wojohowitz** [substack/node-detective#5]
It appears that uglify chokes on hash bangs?

SyntaxError: Unexpected character '#'
  at line 0:0 in expression:

  #!/usr/bin/env node
    at /home/wojtek/Project/Node/INS/node_modules/detective/node_modules/burrito/index.js:16:17
    at /home/wojtek/Project/Node/INS/node_modules/detective/node_modules/burrito/index.js:41:11
    at Function.find (/home/wojtek/Project/Node/INS/node_modules/detective/index.js:12:5)
    at /home/wojtek/Project/Node/INS/node_modules/detective/index.js:4:20
    at /home/wojtek/Project/Node/INS/index.js:42:12
    at /home/wojtek/Project/Node/INS/index.js:52:17
    at Array.forEach (native)
    at Object.start (/home/wojtek/Project/Node/INS/index.js:50:9)
    at Object.<anonymous> (/home/wojtek/Project/Node/INS/bin/ins.js:23:26)
    at Module._compile (module.js:402:26)

I'm getting a list of .js files and passing each one through detective.  my /bin/file.js causes the error here as it begins with #!/usr/bin/env node

**Comment by zertosh** [comment]
This was fixed in https://github.com/substack/node-detective/commit/2487a7b0
